# Generated by Django 4.1.1 on 2023-08-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_type',
            field=models.CharField(choices=[('query', 'Query/Question'), ('testimonial', 'Testimonial')], default='query', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
