# Generated by Django 4.1.1 on 2023-08-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_message_contact_type_message_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='subject',
            field=models.CharField(default='Subject', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='rating',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
    ]
