# Generated by Django 4.1.1 on 2023-08-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_coupon_discount_type_coupon_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount',
        ),
    ]
